version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "178inaba"
    reviewers:
      - "178inaba"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "178inaba"
    reviewers:
      - "178inaba"
